# LICENSE

# Default fetch commands
# Possible options:
# 	install: Shell command used to fetch at install.
# 	update: Shell command used to fetch when updating.
#
# If update directive is not present, then a reinstallation is forced.

# Repository based fetch
svn:
	install: "svn co {{repository-url}} {{name}}"
	update: "svn up"

git:
	install: "git clone {{repository-url}} {{name}}"
	update: "git stash && git pull && git stash pop"

hg:
	install: "hg clone {{repository-url}} {{name}}"
	update: "hg pull"

# Web fetch
http:
	install: "wget {{tool-url}} -O {{name}}"

http-tar:
	install: ""

http-zip:
	install: ""
